SELECT * FROM TAB;

DESC EMPLOYEES;

SELECT * FROM EMPLOYEES;

--직원 번호가 100인 사람을 출력
SELECT *
FROM employees
WHERE EMPLOYEE_ID = 100;

-- King
SELECT *
FROM employees
WHERE LAST_NAME = 'King';

-- 월급순 내림차순으로 직원 정보를 출력 (107명)
SELECT   EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID
FROM     EMPLOYEES
ORDER BY salary ASC; -- DESC : 내림차순 / ASC : 오름차순

-- 월급순 내림차순으로 월급이 5000이상인 직원 정보를 출력 (58명)
SELECT   EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID
FROM     EMPLOYEES
WHERE    SALARY >= 5000
ORDER BY salary ASC; -- DESC : 내림차순 / ASC : 오름차순

-- 전화번호에 010이 포함된 직원
SELECT   EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER
FROM     EMPLOYEES
WHERE    PHONE_NUMBER LIKE '%010%'
ORDER BY PHONE_NUMBER ASC;

-- 50번 부서의 직원을 출력해라
SELECT   EMPLOYEE_ID                      "사 번",    -- 사번 : ALIAS, 별칭
         FIRST_NAME || ' ' || LAST_NAME   "이 름",    -- "" : 문자 사이의 공백을 사용할 때 필요    
         DEPARTMENT_ID                    부서번호
FROM     EMPLOYEES
WHERE    DEPARTMENT_ID = 50
-- ORDER BY FIRST_NAME || ' ' || LAST_NAME ASC;
ORDER BY FIRST_NAME ASC, LAST_NAME ASC;

-- 부서가 없는 직원을 출력
SELECT   EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM     EMPLOYEES
WHERE    DEPARTMENT_ID Is null;