 TUSER
 아이디  문자(20)    필수입력 중복방지
 이름    문자(30)    필수입력
 이메일  문자(320)   중복방지
 
 DROP TABLE TUSER;
 
 CREATE TABLE TUSER (
 USERID    VARCHAR2(20)  NOT NULL PRIMARY KEY,
 USERNAME  VARCHAR2(30)  NOT NULL,
 EMAIL     VARCHAR2(320) UNIQUE
 );
 
 INSERT INTO TUSER (USERID, USERNAME, EMAIL) VALUES ('SKY', '스카이', 'sky@green.com');
 INSERT INTO TUSER (USERID, USERNAME, EMAIL) VALUES ('SKY2', '스카이2', 'sky2@green.com');
 INSERT INTO TUSER (USERID, USERNAME, EMAIL) VALUES ('SKY3', '스카이3', 'sky3@green.com');
 INSERT INTO TUSER (USERID, USERNAME, EMAIL) VALUES ('SKY4', '스카이4', 'sky4@green.com');
 INSERT INTO TUSER (USERID, USERNAME, EMAIL) VALUES ('SKY5', '스카이5', 'sky5@green.com');
 COMMIT;
 INSERT INTO TUSER (USERID, USERNAME, EMAIL) VALUES ('sea2', '바다2', 'sea2@green.com');
 SELECT * FROM TUSER;
 
 SELECT * FROM  TUSER WHERE USERID = 'SKY';
 
 UPDATE TUSER SET    USERNAME = '바다3' WHERE  USERNAME = '바다2';
 
 DELETE FROM TUSER WHERE USERID = 'sea2';
 ROLLBACK;